apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-smee-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: smee-deployment-replicas-alerts
    interval: 1m
    rules:
    - alert: SmeeDeploymentReplicasMismatch
      expr: kube_deployment_spec_replicas{namespace=~"smee.*"} != kube_deployment_status_replicas_available{namespace=~"smee.*"}
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Smee deployment {{ $labels.namespace }}/{{ $labels.deployment }} replicas mismatch
        description: >-
          The number of replicas defined in {{ $labels.namespace }}/{{ $labels.deployment }}
          on cluster {{ $labels.source_cluster }} is different than the actual number of replicas
        alert_routing_key: '{{ $labels.namespace }}'
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/o11y/alert-rule-SmeeDeploymentMismatch.md
