apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-konflux-up-grafana-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: konflux_up_grafana_alerts
    interval: 1m
    rules:
    - alert: KonfluxUpGrafanaAlert
      expr: absent(konflux_up{service="grafana", check="prometheus-appstudio-ds"}) == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Availability metric 'konflux_up' is missing.
        description: >-
          Availability metric 'konflux_up' is missing for check {{ $labels.check }}
          on service {{ $labels.service }} for more than 5 minutes.
        alert_routing_key: 'appstudio-grafana'
