apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-exporter-service-monitor.yaml
- prometheus-exporter-service.yaml
images:
- name: exporter
  newName: quay.io/redhat-appstudio/o11y
  newTag: latest
