apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: appstudio-grafana-datasource-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  namespace: appstudio-grafana-datasource-exporter
  annotations:
    kubernetes.io/service-account.name: metrics-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exporter-role-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: exporter-role-binding-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exporter-role-metrics-reader
subjects:
- kind: ServiceAccount
  name: metrics-reader
  namespace: appstudio-grafana-datasource-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: o11y-servicemonitor
  namespace: appstudio-grafana-datasource-exporter
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenSecret:
      name: "metrics-reader"
      key: token
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app: grafana-datasource-exporter
