# Metric format needed
# redhat_appstudio_remotesecret_secretstorage_system_available(service="remote-secret-controller-manager-metrics-service") -> konflux_up(service="remote-secret-controller-manager-metrics-service", check="secretstorage")
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-remotesecret-availability
  labels:
    tenant: rhtap
spec:
  groups:
    - name: remotesecret_secretstorage_availability
      interval: 1m
      rules:
        - record: konflux_up
          expr: label_replace(redhat_appstudio_remotesecret_secretstorage_system_available, "check", "secretstorage", "","")
