apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pod-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: pod_alerts
    interval: 1m
    rules:
    - alert: UnschedulablePods
      expr: last_over_time(kube_pod_status_unschedulable{namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"}[5m]) == 1
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: Pod {{ $labels.pod }} cannot be scheduled.
        description: >-
          Pod {{ $labels.pod }} for namespace {{ $labels.namespace }} on cluster
          {{ $labels.source_cluster }} is unscheduled for more than 30 minutes.
          Related SOP:
          https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/o11y/alert-rule-unschedualablePods.md
    - alert: CrashLoopBackOff
      expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"}[5m]) >= 1
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Pod {{ $labels.pod }} is crash looping
        description: >-
          Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is in
          waiting state (reason: 'CrashLoopBackOff') on cluster
          {{ $labels.source_cluster }} for more than 15 minutes. Related SOP:
          https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/o11y/alert-rule-crashLoopBackOff.md
    - alert: PodsNotReady
      expr: |
            kube_pod_status_phase{phase=~"Pending|Unknown|Failed", namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"} == 1
            unless ignoring (phase) (kube_pod_status_unschedulable == 1)
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: >-
          Pod {{ $labels.pod }} is not ready
        description: >-
          Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} on cluster {{ $labels.source_cluster }} is
          not ready for more than 15 minutes. Related SOP:
          https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/o11y/alert-rule-PodsNotReady.md
