apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pv-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: pv_alerts
    interval: 1m
    rules:
    - alert: PersistentVolumeIssues
      expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending", namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Persistent Volume {{ $labels.persistentvolume }} is in {{ $labels.phase }} phase for more than 5 minutes"
        description: "Persistent Volume {{ $labels.persistentvolume }} in namespace {{ $labels.namespace }} on cluster {{ $labels.source_cluster }} is in {{ $labels.phase }} phase for more than 5 minutes"
